<?php

/**
 * @file
 * Code for the NNELS Menu Structure feature.
 */

include_once 'nnels_menu_structure.features.inc';

/**
 * Implements hook_enable().
 */

function nnels_menu_structure_menu_enable() {
  $block_ids = variable_get('menu_block_ids');
  $migrated_ids = array(5, 6, 7, 8, 9, 10);
  foreach ($migrated_ids as $id) {
		$block_ids[] = $id;
  }
  variable_set('menu_block_ids', $block_ids);
}
