<?php
/**
 * @file
 * nnels_docs.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function nnels_docs_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_dc_creator'.
  $field_bases['field_dc_creator'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_dc_creator',
    'field_permissions' => array(
      'type' => 0,
    ),
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'max_length' => 255,
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  // Exported field_base: 'field_s3_file_upload'.
  $field_bases['field_s3_file_upload'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_s3_file_upload',
    'field_permissions' => array(
      'type' => 2,
    ),
    'indexes' => array(
      'fid' => array(
        0 => 'fid',
      ),
    ),
    'locked' => 0,
    'module' => 'file',
    'settings' => array(
      'display_default' => 0,
      'display_field' => 0,
      'entity_translation_sync' => array(
        0 => 'fid',
      ),
      'storage_class' => array(
        'class_id' => 1,
        'current_class_id' => 1,
      ),
      'uri_scheme' => 's3',
    ),
    'translatable' => 0,
    'type' => 'file',
  );

  return $field_bases;
}
